os: linux
dist: bionic
language: python
python: 3.8
cache: pip
before_install: pip install --upgrade pip setuptools six
install: 
  - pip install -r requirements.txt
before_script:
  - black --check . || true
